### ISSUE TITLE
Add support for embeds_one and embeds_many

### ISSUE THREAD

**Issue by skovmand** [wise-home/wise_homex#117]
Currently we get the following error when using `embeds_one` and `embeds_many` i `JSONParser`. The attempted query was for a `get_wmbus_message_query/3` call. The code for the call can be found on the issue https://github.com/wise-home/wise_homex/pull/116

@lasseebert Will you take a look at it?

```
2020-01-09 13:26:35.893000 UTC [ERROR] [guest] <0.663.0> :gen_server: GenServer #PID<0.663.0> terminating
** (UndefinedFunctionError) function WiseHomex.Gateway.cast/1 is undefined or private
    (wise_homex) WiseHomex.Gateway.cast(nil)
    (wise_homex) lib/wise_homex/json_parser.ex:337: WiseHomex.JSONParser.parse_embed/2
    (wise_homex) lib/wise_homex/json_parser.ex:313: WiseHomex.JSONParser.convert_ecto_embedded_value/4
    (wise_homex) lib/wise_homex/json_parser.ex:229: WiseHomex.JSONParser.add_related_entities/2
    (wise_homex) lib/wise_homex/json_parser.ex:170: WiseHomex.JSONParser.add_relations/3
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (wise_homex) lib/wise_homex/json_parser.ex:64: WiseHomex.JSONParser.parse/1
    (wise_homex) lib/wise_homex/response_parser.ex:39: WiseHomex.ResponseParser.parse_json_response/2
    (arwen) lib/arwen_web/live/person_on_site_live.ex:69: ArwenWeb.PersonOnSiteLive.handle_info/2
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:106: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by skovmand** [comment]
The JSON response that fails is

```
%{
  "data" => %{
    "attributes" => %{"save" => true, "timeout" => 30000},
    "id" => "",
    "relationships" => %{
      "gateway" => %{"data" => %{"id" => "7", "type" => "gateways"}}
    },
    "type" => "wmbus-message-queries"
  },
  "jsonapi" => %{"version" => "1.0"}
}
```

**Comment by lasseebert** [comment]
Fixed as part of https://github.com/wise-home/wise_homex/pull/116
